### ISSUE TITLE
Multi Install Issue zmzimletctl deploy

### ISSUE THREAD

**Issue by vnngoanhtuan** [Zimbra-Community/zimbra-foss-2fa#36]
Hi Pro,

I have zimbra multi server installation: 02 ldap ; 02 mailbox server ;  02 mta and proxy. When I run command as below in  ( zimbra version 8.8.15 + centos 7 x64)

- mailbox server, the error is happen.

$zmzimletctl deploy tk_barrydegraaff_2fa.zip

java.util.zip.ZipException: zip END header not found
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1470)
        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1371)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1378)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1209)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1172)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:719)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:239)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:169)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:346)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:317)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:283)
        at com.zimbra.cs.zimlet.ZimletFile.initialize(ZimletFile.java:210)
        at com.zimbra.cs.zimlet.ZimletFile.initialize(ZimletFile.java:175)
        at com.zimbra.cs.zimlet.ZimletFile.<init>(ZimletFile.java:156)
        at com.zimbra.cs.zimlet.ZimletUtil.dispatch(ZimletUtil.java:1910)
        at com.zimbra.cs.zimlet.ZimletUtil.main(ZimletUtil.java:2012)

[] ERROR: Error
java.util.zip.ZipException: zip END header not found
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1470)
        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1371)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1378)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1209)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1172)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:719)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:239)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:169)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:346)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:317)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:283)
        at com.zimbra.cs.zimlet.ZimletFile.initialize(ZimletFile.java:210)
        at com.zimbra.cs.zimlet.ZimletFile.initialize(ZimletFile.java:175)
        at com.zimbra.cs.zimlet.ZimletFile.<init>(ZimletFile.java:156)
        at com.zimbra.cs.zimlet.ZimletUtil.dispatch(ZimletUtil.java:1910)
        at com.zimbra.cs.zimlet.ZimletUtil.main(ZimletUtil.java:2012)

- mta and proxy server, the error is happen.

$zmzimletctl deploy tk_barrydegraaff_2fa.zip

[] INFO: Deploying Zimlet tk_barrydegraaff_2fa in LDAP.
[] INFO: Installing Zimlet tk_barrydegraaff_2fa on this host.
java.io.IOException: No such file or directory
        at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
        at java.base/java.io.File.createNewFile(File.java:1024)
        at com.zimbra.cs.zimlet.ZimletUtil.writeFile(ZimletUtil.java:760)
        at com.zimbra.cs.zimlet.ZimletUtil.installZimletLocally(ZimletUtil.java:706)
        at com.zimbra.cs.zimlet.ZimletUtil.deployZimletLocally(ZimletUtil.java:627)
        at com.zimbra.cs.zimlet.ZimletUtil.dispatch(ZimletUtil.java:1910)
        at com.zimbra.cs.zimlet.ZimletUtil.main(ZimletUtil.java:2012)

[] ERROR: Error
java.io.IOException: No such file or directory
        at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
        at java.base/java.io.File.createNewFile(File.java:1024)
        at com.zimbra.cs.zimlet.ZimletUtil.writeFile(ZimletUtil.java:760)
        at com.zimbra.cs.zimlet.ZimletUtil.installZimletLocally(ZimletUtil.java:706)
        at com.zimbra.cs.zimlet.ZimletUtil.deployZimletLocally(ZimletUtil.java:627)
        at com.zimbra.cs.zimlet.ZimletUtil.dispatch(ZimletUtil.java:1910)
        at com.zimbra.cs.zimlet.ZimletUtil.main(ZimletUtil.java:2012)

So is that right to Install the Zimlets? or fix the issues?

Thanks,
Tuan Ngo

**Comment by vnngoanhtuan** [comment]
Dear All,

I have checked and found the download files are some issues and now with new download files, the issues have been solved.

Thanks,
Tuan Ngo
