### ISSUE TITLE
error after installing java extension

### ISSUE THREAD

**Issue by vuducanha2** [Zimbra-Community/zimbra-foss-2fa#9]
Hi @barrydegraaff !
Everything is fine when I install it to the 18th step, but after the java extension, my zimbra server has an error, the web client cannot log in, the admin page is empty,I using  CentOS 7.x and Zimbra 8.8.6. The command  zmprov does not work and log mailbox.log  the following error: 
2019-06-12 07:46:48,977 FATAL [main] [] soap - Unable to start servlet
java.lang.NoClassDefFoundError: Could not initialize class com.zimbra.cs.extension.ExtensionUtil
	at com.zimbra.cs.util.Zimbra.startup(Zimbra.java:268)
	at com.zimbra.cs.util.Zimbra.startup(Zimbra.java:179)
	at com.zimbra.soap.SoapServlet.init(SoapServlet.java:126)
	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:626)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:405)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:875)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:346)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1380)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:772)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:259)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:518)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)

. Pls help me. thanks you

**Comment by vuducanha2** [comment]
Before i install java extension, i saw log in mailbox.log follow:

com.zimbra.common.service.ServiceException: unknown document: privacyIdea
ExceptionId:qtp335471116-316:https:https://10.60.156.27/service/soap/privacyIdea:1560243044722:dd37999d84271d09
Code:service.UNKNOWN_DOCUMENT
	at com.zimbra.common.service.ServiceException.UNKNOWN_DOCUMENT(ServiceException.java:302)
	at com.zimbra.soap.SoapEngine.dispatchRequest(SoapEngine.java:530)
	at com.zimbra.soap.SoapEngine.dispatch(SoapEngine.java:460)
	at com.zimbra.soap.SoapEngine.dispatch(SoapEngine.java:273)
	at com.zimbra.soap.SoapServlet.doWork(SoapServlet.java:303)
	at com.zimbra.soap.SoapServlet.doPost(SoapServlet.java:213)

**Comment by barrydegraaff** [comment]
This is the error you see if you install the Zimlet, but not the extension. 

You should install the extension and restart mailbox for it to work, or 
just use the installer script.

**Comment by barrydegraaff** [comment]
Please remove all components of the 2FA, and then first upgrade your Zimbra 
server to the latest version. 

Make sure to rm -Rf /opt/zimbra/lib/ext/zimbraprivacyidea then restart mailbox 

using zmmailboxdctl restart 

Then upgrade Zimbra to 8.8.8 patch 2 and then install the 2FA.

**Comment by vuducanha2** [comment]
Hi @barrydegraaff ,
Thanks you for support. I  removed container, network privacyidea  and install zimbra 8.8.11 Patch 5 then install following your guide but this still not working. Log mailbox same #1.

**Comment by barrydegraaff** [comment]
It's because you need 8.8.12, I made a typo earlier. 

This has to do with the Java version shipped in Zimbra... that has had a mayor update in 8.8.12. 


Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by vuducanha2** [comment]
Thanks for your help , I followed it, even I recreated another VM Centos 7 and installed Zimbra 8.8.12 patch 2, but then it still made a mistake like # 1 (error appears after I install Java Extension) and this is a log mailbox:


`2019-06-13 19:39:58,745 WARN  [main] [] ZimbraHttpConnectionManager - Cannot start a second http client idle connection reaper thread while another one is running.
2019-06-13 19:39:58,745 WARN  [main] [] ZimbraHttpConnectionManager - Cannot start a second http client idle connection reaper thread while another one is running.
2019-06-13 19:39:58,745 WARN  [main] [] ephemeral - Replacing ephemeral factory class 'com.zimbra.cs.ephemeral.LdapEphemeralStore$Factory' registered for 'ldap' with 'com.zimbra.cs.ephemeral.LdapEphemeralStore$Factory'
2019-06-13 19:39:58,745 FATAL [main] [] soap - Unable to start servlet
java.lang.NoClassDefFoundError: Could not initialize class com.zimbra.cs.extension.ExtensionUtil
	at com.zimbra.cs.util.Zimbra.startup(Zimbra.java:266)
	at com.zimbra.cs.util.Zimbra.startup(Zimbra.java:177)
	at com.zimbra.soap.SoapServlet.init(SoapServlet.java:129)
	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:626)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:405)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:875)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:346)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1380)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:772)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:259)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:518)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
`

and 

`2019-06-13 19:41:59,550 ERROR [qtp928294079-97:https:https://10.60.156.24/] [] webclient - Unable to get domain config
com.zimbra.common.service.ServiceException: error while proxying request to target server: HTTP/1.1 503 Service Unavailable
ExceptionId:qtp928294079-97:https:https://10.60.156.24/:1560429719549:086a569f8bee3c17
Code:service.PROXY_ERROR Arg:(url, STR, "https://localhost:7071/service/admin/soap/AuthRequest")
	at com.zimbra.common.service.ServiceException.PROXY_ERROR(ServiceException.java:379)
	at com.zimbra.common.soap.SoapHttpTransport.invoke(SoapHttpTransport.java:296)
	at com.zimbra.common.soap.SoapHttpTransport.invoke(SoapHttpTransport.java:193)
	at com.zimbra.common.soap.SoapHttpTransport.invoke(SoapHttpTransport.java:186)
	at com.zimbra.common.soap.SoapTransport.invoke(SoapTransport.java:447)
	at com.zimbra.common.soap.SoapTransport.invokeWithoutSession(SoapTransport.java:433)
	at com.zimbra.cs.account.soap.SoapProvisioning.invokeRequest(SoapProvisioning.java:624)
	at com.zimbra.cs.account.soap.SoapProvisioning.invoke(SoapProvisioning.java:669)
	at com.zimbra.cs.account.soap.SoapProvisioning.soapAdminAuthenticate(SoapProvisioning.java:559)
	at com.zimbra.cs.account.soap.SoapProvisioning.soapZimbraAdminAuthenticate(SoapProvisioning.java:588)
	at com.zimbra.cs.servlet.SetHeaderFilter.getResponseHeaders(SetHeaderFilter.java:109)
	at com.zimbra.cs.servlet.SetHeaderFilter.addZimbraResponseHeaders(SetHeaderFilter.java:96)
	at com.zimbra.cs.servlet.SetHeaderFilter.doFilter(SetHeaderFilter.java:82)
`

**Comment by barrydegraaff** [comment]
These errors are all in classes unrelated to 2FA extension. 

Does it work if 2FA is not installed? 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by vuducanha2** [comment]
Befor instal 2FA, zimbra running.
Then install file script 2fa-installer.sh notify error when login in web .
![install 2fa error](https://user-images.githubusercontent.com/44759826/59481814-175e4680-8e90-11e9-9089-fcb7338470e6.PNG)

Then i check log mailbox.log 
```

019-06-14 10:27:45,661 WARN  [qtp1647809929-25:https:https://10.60.156.24/] [] webclient - system failure: error while proxying request to target server: HTTP/1.1 503 Service Unavailable
com.zimbra.common.service.ServiceException: system failure: error while proxying request to target server: HTTP/1.1 503 Service Unavailable
ExceptionId:qtp1647809929-25:https:https://10.60.156.24/:1560482865658:a96e886c0ca71f06
Code:service.FAILURE
	at com.zimbra.common.service.ServiceException.FAILURE(ServiceException.java:288)
	at com.zimbra.client.ZMailbox.invoke(ZMailbox.java:1004)
	at com.zimbra.client.ZMailbox.invoke(ZMailbox.java:980)
	at com.zimbra.client.ZMailbox.invokeJaxbToElement(ZMailbox.java:963)
	at com.zimbra.client.ZMailbox.invokeJaxb(ZMailbox.java:968)
	at com.zimbra.client.ZMailbox.authByPassword(ZMailbox.java:878)
	at com.zimbra.client.ZMailbox.<init>(ZMailbox.java:747)
	at com.zimbra.client.ZMailbox.getMailbox(ZMailbox.java:666)
	at com.zimbra.cs.taglib.tag.LoginTag.doTag(LoginTag.java:199)
	at org.apache.jsp.public_.login_jsp._jspService(login_jsp.java:457)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:438)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
	at org.eclipse.jetty.jsp.JettyJspServlet.service(JettyJspServlet.java:107)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
```

Thanks so much!

**Comment by vuducanha2** [comment]
I checked the log after step by step, before I installed Java Extension, I could still log in Zimbra with OTP code, but select the Zimlet feature and report the Unknow document error.

**Comment by barrydegraaff** [comment]
Is this a multi server Zimbra? 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by vuducanha2** [comment]
It's single server, I just tried to setup 2FA again with Zimbra 8.8.12 patch 3 but it still not working ! 

Mailbox.log : 

`2019-06-14 14:46:38,403 WARN  [qtp928294079-37:https:https://10.60.156.24/] [] webclient - system failure: error while proxying request to target server: HTTP/1.1 503 Service Unavailable
com.zimbra.common.service.ServiceException: system failure: error while proxying request to target server: HTTP/1.1 503 Service Unavailable
ExceptionId:qtp928294079-37:https:https://10.60.156.24/:1560498398399:165af21f2943819e
Code:service.FAILURE
	at com.zimbra.common.service.ServiceException.FAILURE(ServiceException.java:288)
	at com.zimbra.client.ZMailbox.invoke(ZMailbox.java:1004)
	at com.zimbra.client.ZMailbox.invoke(ZMailbox.java:980)
	at com.zimbra.client.ZMailbox.invokeJaxbToElement(ZMailbox.java:963)
	at com.zimbra.client.ZMailbox.invokeJaxb(ZMailbox.java:968)
	at com.zimbra.client.ZMailbox.authByPassword(ZMailbox.java:878)
	at com.zimbra.client.ZMailbox.<init>(ZMailbox.java:747)
	at com.zimbra.client.ZMailbox.getMailbox(ZMailbox.java:666)
	at com.zimbra.cs.taglib.tag.LoginTag.doTag(LoginTag.java:199)
	at org.apache.jsp.public_.login_jsp._jspService(login_jsp.java:457)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:438)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
	at org.eclipse.jetty.jsp.JettyJspServlet.service(JettyJspServlet.java:107)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
`

Thank you

**Comment by barrydegraaff** [comment]
Please send me an ssh access so I can check (info@barrydegraaff.tk) 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by vuducanha2** [comment]
I have been sent a message to you. Pls check your inbox.

Thanks you so much!

**Comment by barrydegraaff** [comment]
A number of permission issues on a non-standard CentOS installation, the installer has been updated to make sure Zimbra can read the extension and patched login/changepass screen
